### PR TITLE
Added Metabase/data dictionary and spelling fixes

### PR DESCRIPTION
**Pull request by JeniferBrown**
## what
* Added Metabase questions
* Made changes to data dictionary
* Corrected spelling errors
* Added some installation instructions
## why
* Continued development of guides

### CODE REVIEW

**Review by jacobcsmith — DISMISSED** [review]

**Comment by jacobcsmith** [comment]
@JeniferBrown the test step failed. Does `npm run build` work for you locally?

**Comment by JeniferBrown** [comment]
@jacobcsmith should be good now

**Review by jacobcsmith — APPROVED** [review]

**Pull request merged**
