### PR TITLE
Feature/Add Sage docs

### PR DESCRIPTION
**Pull request by jacobcsmith**
## what
* Adds the current draft of Sage documentation
* Updates docusaurus config to allow for environment specific baseUrl

## why
* To migrate the existing internal documentation repo to Github

### CODE REVIEW

**Comment by jacobcsmith** [comment]
Errors found in [custom.css](https://app.codacy.com/gh/saic-oss/sage-docs/file/51264609290/issues/source?bid=21448998&fileBranchId=21448998) seem to be an [issue with CSSLint](https://github.com/CSSLint/csslint/issues/720)

**Comment by RothAndrew** [comment]
> Errors found in [custom.css](https://app.codacy.com/gh/saic-oss/sage-docs/file/51264609290/issues/source?bid=21448998&fileBranchId=21448998) seem to be an [issue with CSSLint](https://github.com/CSSLint/csslint/issues/720)

Correct. I unchecked "Prohibit Syntax Errors" in Codacy due to this issue. It shouldn't throw errors for the "expected RBRACE" issues again. Please push a new commit to retrigger the Codacy check

**Comment by jacobcsmith** [comment]
Can we also ignore the console.log errors? The file in question is a utility run via the command line and not included in the built website

**Comment by RothAndrew** [comment]
> Can we also ignore the console.log errors? The file in question is a utility run via the command line and not included in the built website

The whole rule shouldn't be disabled, since it is still very valid for the Docusaurus stuff. The rule comes from ESLint, and you can configure ESLint using methods found here: https://eslint.org/docs/user-guide/configuring

I recommend either creating an .eslintignore file and adding the offending file to it, or an .eslintrc.json if you want to have more refined configuration than just ignoring the whole file

I'm curious though, why is this postman-to-md project being vendored like this rather than using it from its source (wherever that may be)?

**Comment by jacobcsmith** [comment]
Is there a particular eslint config file we use which would match the rules used in Codacy?

We vendored postman-to-md because we needed to tailor the output to fit our needs and the library didn't have a way to customize the output outside of modifying the functions producing the output.

**Comment by RothAndrew** [comment]
> Is there a particular eslint config file we use which would match the rules used in Codacy?
> 
> We vendored postman-to-md because we needed to tailor the output to fit our needs and the library didn't have a way to customize the output outside of modifying the functions producing the output.

Okay. My recommendation would be to fork it to your personal github and make the changes there, then use it like you would use any other NPM tool. We can discuss later on whether it should be added as an open source project in this org.

Doing it this way should solve a lot of these issues since you are trying to have a node app and a web app in the same project.

At the very least, it needs to come out of the `webapp` folder and go into its own folder. Golang uses a folder called `vendor` which might work here (so instead of `/webapp/src/postman-to-md` you'd do `/vendor/postman-to-md`, though even then the projects vendored aren't being changed, just cloned.

If you are okay with moving it out to a different repo, then this should be resolved. If not, then we'll need to come up with a .eslintrc that works for this project (or maybe 2, one for the webapp and one for the vendored tool)

**Comment by RothAndrew** [comment]
Also don't forget to comment `/test`, that's the trigger to get the `Public GitHub/full-ci` pipeline to run. You need to set your org visibility to public for Codefresh to be able to run it though

**Comment by jacobcsmith** [comment]
Ok I'll move the postman to md code to a new repo. I've removed it from this repo for now to allow this PR to pass the checks.

**Review by JeniferBrown — APPROVED** [review]

**Pull request merged**
